apiVersion: v1
name: ses-chart
description: A Helm chart for the ACK service controller for Simple Email Service (SES)
version: 1.0.1
appVersion: 1.0.1
home: https://github.com/aws-controllers-k8s/ses-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/ses-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: SES Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ses-maintainer
keywords:
  - aws
  - kubernetes
  - ses
